### PR TITLE
Fix __defineGeneric not a function 

### LINKED ISSUE #49: `globalScope.__defineGeneric` is not a function
# `globalScope.__defineGeneric` is not a funtion
Hello. **What problem do I try to solve**: we try to migrate our out-of-date flow to the latest version, and on the way installed `ft-flow` to lint it. We have `no-undef` rule, and need to override it for flow internal types, i.e. `$Values<...>`, `$Keys<...>`, ..., because they conflict with eslint's `no-undef` now.
I'm trying to add `ft-flow` to `.eslintrs.js`, which kinda works until I start adding rules beyond recommended extension. My config (relevant parts, I guess):

```javascript
module.exports = {
  parser: 'hermes-eslint',
  parserOptions: {
    ecmaVersion: 9,
    sourceType: 'module',
    ecmaFeatures: {
      jsx: true,
    },
    babelOptions: {
      configFile: path.resolve(__dirname, './babel.config.js'),
    },
  },
  extends: [
    // ...
    'plugin:ft-flow/recommended'
  ],
  plugins: [
    'ft-flow',
    // ...
  ],
  env: {
    browser: true,
    jquery: true,
    node: true,
    jest: true,
    es6: true,
  },
  root: true,
  rules: {
    'ft-flow/use-flow-type': 1,
    'ft-flow/define-flow-type': 1, // this rule breaks
    // ...
  },
  // ...
}
```

The line of code where I get the error (I guess, `$Values<...>` breaks it)
```javascript
export type ResourceType = $Values<typeof RESOURCE_TYPES>
```

```
ESLint: 8.56.0

TypeError: globalScope.__defineGeneric is not a function
Occurred while linting [some js file here]
Rule: "ft-flow/define-flow-type"
    at makeDefined (PATH/node_modules/eslint-plugin-ft-flow/dist/rules/defineFlowType.js:28:21)
    at GenericTypeAnnotation (PATH/node_modules/eslint-plugin-ft-flow/dist/rules/defineFlowType.js:67:9)
    at PATH/node_modules/eslint/lib/linter/timing.js:141:28
    at ruleErrorHandler (PATH/node_modules/eslint/lib/linter/linter.js:1076:28)
    at PATH/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (PATH/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (PATH/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (PATH/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (PATH/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
```

There is similar [issue](https://github.com/gajus/eslint-plugin-flowtype/issues/524) in your legacy (right?) project, but no solutions provided whatsoever. What can I do? Or maybe this is a bug? Thank you in advance.

### PR DESCRIPTION
**Pull request by Brianzchen**
Closes #49 by rewriting the way we identify and then add flow types as defined to the eslint scope

### CODE REVIEW

File: src/rules/defineFlowType.js [hunk 1]
```diff
@@ -3,87 +3,78 @@ const schema = [];
...
     },
-    Program() {
-      globalScope = context.getScope();
+    Program(node) {
+      const newGetScope = context.sourceCode.getScope;
+      if (newGetScope) {
+        globalScope = context.sourceCode.getScope(node);
+      } else {
+        globalScope = context.getScope();
+      }
```
Comment (pieterv) [inline src/rules/defineFlowType.js:73]: @Brianzchen `context.sourceCode` can be undefined in older versions of eslint so this code causes the following error: `TypeError: Cannot read properties of undefined (reading 'getScope')`.

I think you want something like:
```
      if (context.sourceCode != null && context.sourceCode.getScope != nul) {
        globalScope = context.sourceCode.getScope(node);
      } else {
        globalScope = context.getScope();
      }
```
