### PR TITLE
Lint fixes

### LINKED ISSUE #7: Fix all lint errors and enable as part of build

### PR DESCRIPTION
**Pull request by Brianzchen**
Closes #7

### CODE REVIEW

File: src/rules/noFlowFixMeComments.js [hunk 1]
```diff
@@ -6,23 +6,23 @@ const schema = [
...
-  return node && node.type === 'Identifier' && node.name.match(name);
-};
+const isIdentifier = (node, name) => (
+  node && node.type === 'Identifier' && node.name.match(name)
+);
 
 const create = (context) => {
   const allowedPattern = context.options[0] ? new RegExp(context.options[0], 'u') : null;
-  const extraMessage = allowedPattern ? ' Fix it or match `' + allowedPattern.toString() + '`.' : '';
+  const extraMessage = allowedPattern ? ` Fix it or match \`${allowedPattern.toString()}\`.` : '';
```
Comment (angelica-bocanegra) [inline src/rules/noFlowFixMeComments.js:15]:
```suggestion
  const extraMessage = allowedPattern ? ` Fix it or match \'${allowedPattern.toString()}\'.` : '';
```
Maybe instead of a backtick we can use single quotations to match the format of other messages

Comment (angelica-bocanegra) [reply src/rules/noFlowFixMeComments.js:15]: btw the test would then need to be updated if it is changed from backticks - _this change won't provide much value_ but we should probably have standards in the error messaging

**Review by angelica-bocanegra — APPROVED** [review]
LGTM 🚀
